<<<<<<< HEAD:TravelSite/Migrations/201912131951501_ThirdMigration.Designer.cs
// <auto-generated />
namespace TravelSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ThirdMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThirdMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131951501_ThirdMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace TravelSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ThirdMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThirdMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201912132030045_ThirdMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> 265781860ad710c0d1d622726e64ffb6180605f0:TravelSite/Migrations/201912132030045_ThirdMigration.Designer.cs
